image: "alpine:latest"
    
pages:
  stage: deploy
  script:
    - apk add vala libgee-dev graphviz graphviz-dev graphviz-libs
    - valadoc src/*.vala --pkg=sdl2 --pkg=gee-0.8 -o burger
    - mv burger public
    - ls -la
    - echo "Pages deployment job at ${CI_PAGES_URL}"
  artifacts:
    paths:
      - public
  only:
  - master
