image: "alpine:latest"
    
pages:
  stage: deploy
  script:
    - apk add vala
    - valadoc src/*.vala --pkg=sdl2 -o burger
    - mv burger public
    - ls -la
    - echo "Pages deployment job at ${CI_PAGES_URL}"
  artifacts:
    paths:
      - public
