public enum Vgl.EventType {
	APP_DIDENTERBACKGROUND = SDL.EventType.APP_DIDENTERBACKGROUND,
	APP_DIDENTERFOREGROUND = SDL.EventType.APP_DIDENTERFOREGROUND,
	APP_LOWMEMORY = SDL.EventType.APP_LOWMEMORY,
	APP_TERMINATING = SDL.EventType.APP_TERMINATING,
	APP_WILLENTERBACKGROUND = SDL.EventType.APP_WILLENTERBACKGROUND,
	APP_WILLENTERFOREGROUND = SDL.EventType.APP_WILLENTERFOREGROUND,
	AUDIODEVICEADDED = SDL.EventType.AUDIODEVICEADDED,
	AUDIODEVICEREMOVED = SDL.EventType.AUDIODEVICEREMOVED,
	CLIPBOARDUPDATE = SDL.EventType.CLIPBOARDUPDATE,
	CONTROLLERAXISMOTION = SDL.EventType.CONTROLLERAXISMOTION,
	CONTROLLERBUTTONDOWN = SDL.EventType.CONTROLLERBUTTONDOWN,
	CONTROLLERBUTTONUP = SDL.EventType.CONTROLLERBUTTONUP,
	CONTROLLERDEVICEADDED = SDL.EventType.CONTROLLERDEVICEADDED,
	CONTROLLERDEVICEREMAPPED = SDL.EventType.CONTROLLERDEVICEREMAPPED,
	CONTROLLERDEVICEREMOVED = SDL.EventType.CONTROLLERDEVICEREMOVED,
	DOLLARGESTURE = SDL.EventType.DOLLARGESTURE,
	DOLLARRECORD = SDL.EventType.DOLLARRECORD,
	DROPBEGIN = SDL.EventType.DROPBEGIN,
	DROPCOMPLETE = SDL.EventType.DROPCOMPLETE,
	DROPFILE = SDL.EventType.DROPFILE,
	DROPTEXT = SDL.EventType.DROPTEXT,
	FINGERDOWN = SDL.EventType.FINGERDOWN,
	FINGERMOTION = SDL.EventType.FINGERMOTION,
	FINGERUP = SDL.EventType.FINGERUP,
	FIRSTEVENT = SDL.EventType.FIRSTEVENT,
	JOYAXISMOTION = SDL.EventType.JOYAXISMOTION,
	JOYBALLMOTION = SDL.EventType.JOYBALLMOTION,
	JOYBUTTONDOWN = SDL.EventType.JOYBUTTONDOWN,
	JOYBUTTONUP = SDL.EventType.JOYBUTTONUP,
	JOYDEVICEADDED = SDL.EventType.JOYDEVICEADDED,
	JOYDEVICEREMOVED = SDL.EventType.JOYDEVICEREMOVED,
	JOYHATMOTION = SDL.EventType.JOYHATMOTION,
	KEYDOWN = SDL.EventType.KEYDOWN,
	KEYMAPCHANGED = SDL.EventType.KEYMAPCHANGED,
	KEYUP = SDL.EventType.KEYUP,
	LASTEVENT = SDL.EventType.LASTEVENT,
	MOUSEBUTTONDOWN = SDL.EventType.MOUSEBUTTONDOWN,
	MOUSEBUTTONUP = SDL.EventType.MOUSEBUTTONUP,
	MOUSEMOTION = SDL.EventType.MOUSEMOTION,
	MOUSEWHEEL = SDL.EventType.MOUSEWHEEL,
	MULTIGESTURE = SDL.EventType.MULTIGESTURE,
	QUIT = SDL.EventType.QUIT,
	RENDER_DEVICE_RESET = SDL.EventType.RENDER_DEVICE_RESET,
	RENDER_TARGETS_RESET = SDL.EventType.RENDER_TARGETS_RESET,
	SYSWMEVENT = SDL.EventType.SYSWMEVENT,
	TEXTEDITING = SDL.EventType.TEXTEDITING,
	TEXTINPUT = SDL.EventType.TEXTINPUT,
	USEREVENT = SDL.EventType.USEREVENT,
	WINDOWEVENT = SDL.EventType.WINDOWEVENT
}

public enum Vgl.KeyCode {
	AC_BACK = SDL.Input.Keycode.AC_BACK,
	AC_BOOKMARKS = SDL.Input.Keycode.AC_BOOKMARKS,
	AC_FORWARD = SDL.Input.Keycode.AC_FORWARD,
	AC_HOME = SDL.Input.Keycode.AC_HOME,
	AC_REFRESH = SDL.Input.Keycode.AC_REFRESH,
	AC_SEARCH = SDL.Input.Keycode.AC_SEARCH,
	AC_STOP = SDL.Input.Keycode.AC_STOP,
	AGAIN = SDL.Input.Keycode.AGAIN,
	ALTERASE = SDL.Input.Keycode.ALTERASE,
	AMPERSAND = SDL.Input.Keycode.AMPERSAND,
	APPLICATION = SDL.Input.Keycode.APPLICATION,
	ASTERISK = SDL.Input.Keycode.ASTERISK,
	AT = SDL.Input.Keycode.AT,
	AUDIOMUTE = SDL.Input.Keycode.AUDIOMUTE,
	AUDIONEXT = SDL.Input.Keycode.AUDIONEXT,
	AUDIOPLAY = SDL.Input.Keycode.AUDIOPLAY,
	AUDIOPREV = SDL.Input.Keycode.AUDIOPREV,
	AUDIOSTOP = SDL.Input.Keycode.AUDIOSTOP,
	BACKQUOTE = SDL.Input.Keycode.BACKQUOTE,
	BACKSLASH = SDL.Input.Keycode.BACKSLASH,
	BACKSPACE = SDL.Input.Keycode.BACKSPACE,
	BRIGHTNESSDOWN = SDL.Input.Keycode.BRIGHTNESSDOWN,
	BRIGHTNESSUP = SDL.Input.Keycode.BRIGHTNESSUP,
	CALCULATOR = SDL.Input.Keycode.CALCULATOR,
	CANCEL = SDL.Input.Keycode.CANCEL,
	CAPSLOCK = SDL.Input.Keycode.CAPSLOCK,
	CARET = SDL.Input.Keycode.CARET,
	CLEAR = SDL.Input.Keycode.CLEAR,
	CLEARAGAIN = SDL.Input.Keycode.CLEARAGAIN,
	COLON = SDL.Input.Keycode.COLON,
	COMMA = SDL.Input.Keycode.COMMA,
	COMPUTER = SDL.Input.Keycode.COMPUTER,
	COPY = SDL.Input.Keycode.COPY,
	CRSEL = SDL.Input.Keycode.CRSEL,
	CURRENCYSUBUNIT = SDL.Input.Keycode.CURRENCYSUBUNIT,
	CURRENCYUNIT = SDL.Input.Keycode.CURRENCYUNIT,
	CUT = SDL.Input.Keycode.CUT,
	DECIMALSEPARATOR = SDL.Input.Keycode.DECIMALSEPARATOR,
	DELETE = SDL.Input.Keycode.DELETE,
	DISPLAYSWITCH = SDL.Input.Keycode.DISPLAYSWITCH,
	DOLLAR = SDL.Input.Keycode.DOLLAR,
	DOWN = SDL.Input.Keycode.DOWN,
	EIGHT = SDL.Input.Keycode.EIGHT,
	EJECT = SDL.Input.Keycode.EJECT,
	END = SDL.Input.Keycode.END,
	EQUALS = SDL.Input.Keycode.EQUALS,
	ESCAPE = SDL.Input.Keycode.ESCAPE,
	EXCLAIM = SDL.Input.Keycode.EXCLAIM,
	EXECUTE = SDL.Input.Keycode.EXECUTE,
	EXSEL = SDL.Input.Keycode.EXSEL,
	F1 = SDL.Input.Keycode.F1,
	F10 = SDL.Input.Keycode.F10,
	F11 = SDL.Input.Keycode.F11,
	F12 = SDL.Input.Keycode.F12,
	F13 = SDL.Input.Keycode.F13,
	F14 = SDL.Input.Keycode.F14,
	F15 = SDL.Input.Keycode.F15,
	F16 = SDL.Input.Keycode.F16,
	F17 = SDL.Input.Keycode.F17,
	F18 = SDL.Input.Keycode.F18,
	F19 = SDL.Input.Keycode.F19,
	F2 = SDL.Input.Keycode.F2,
	F20 = SDL.Input.Keycode.F20,
	F21 = SDL.Input.Keycode.F21,
	F22 = SDL.Input.Keycode.F22,
	F23 = SDL.Input.Keycode.F23,
	F24 = SDL.Input.Keycode.F24,
	F3 = SDL.Input.Keycode.F3,
	F4 = SDL.Input.Keycode.F4,
	F5 = SDL.Input.Keycode.F5,
	F6 = SDL.Input.Keycode.F6,
	F7 = SDL.Input.Keycode.F7,
	F8 = SDL.Input.Keycode.F8,
	F9 = SDL.Input.Keycode.F9,
	FIND = SDL.Input.Keycode.FIND,
	FIVE = SDL.Input.Keycode.FIVE,
	FOUR = SDL.Input.Keycode.FOUR,
	GREATER = SDL.Input.Keycode.GREATER,
	HASH = SDL.Input.Keycode.HASH,
	HELP = SDL.Input.Keycode.HELP,
	HOME = SDL.Input.Keycode.HOME,
	INSERT = SDL.Input.Keycode.INSERT,
	KBDILLUMDOWN = SDL.Input.Keycode.KBDILLUMDOWN,
	KBDILLUMTOGGLE = SDL.Input.Keycode.KBDILLUMTOGGLE,
	KBDILLUMUP = SDL.Input.Keycode.KBDILLUMUP,
	KP_0 = SDL.Input.Keycode.KP_0,
	KP_00 = SDL.Input.Keycode.KP_00,
	KP_000 = SDL.Input.Keycode.KP_000,
	KP_1 = SDL.Input.Keycode.KP_1,
	KP_2 = SDL.Input.Keycode.KP_2,
	KP_3 = SDL.Input.Keycode.KP_3,
	KP_4 = SDL.Input.Keycode.KP_4,
	KP_5 = SDL.Input.Keycode.KP_5,
	KP_6 = SDL.Input.Keycode.KP_6,
	KP_7 = SDL.Input.Keycode.KP_7,
	KP_8 = SDL.Input.Keycode.KP_8,
	KP_9 = SDL.Input.Keycode.KP_9,
	KP_A = SDL.Input.Keycode.KP_A,
	KP_AMPERSAND = SDL.Input.Keycode.KP_AMPERSAND,
	KP_AT = SDL.Input.Keycode.KP_AT,
	KP_B = SDL.Input.Keycode.KP_B,
	KP_BACKSPACE = SDL.Input.Keycode.KP_BACKSPACE,
	KP_BINARY = SDL.Input.Keycode.KP_BINARY,
	KP_C = SDL.Input.Keycode.KP_C,
	KP_CLEAR = SDL.Input.Keycode.KP_CLEAR,
	KP_CLEARENTRY = SDL.Input.Keycode.KP_CLEARENTRY,
	KP_COLON = SDL.Input.Keycode.KP_COLON,
	KP_COMMA = SDL.Input.Keycode.KP_COMMA,
	KP_D = SDL.Input.Keycode.KP_D,
	KP_DBLAMPERSAND = SDL.Input.Keycode.KP_DBLAMPERSAND,
	KP_DBLVERTICALBAR = SDL.Input.Keycode.KP_DBLVERTICALBAR,
	KP_DECIMAL = SDL.Input.Keycode.KP_DECIMAL,
	KP_DIVIDE = SDL.Input.Keycode.KP_DIVIDE,
	KP_E = SDL.Input.Keycode.KP_E,
	KP_ENTER = SDL.Input.Keycode.KP_ENTER,
	KP_EQUALS = SDL.Input.Keycode.KP_EQUALS,
	KP_EQUALSAS400 = SDL.Input.Keycode.KP_EQUALSAS400,
	KP_EXCLAM = SDL.Input.Keycode.KP_EXCLAM,
	KP_F = SDL.Input.Keycode.KP_F,
	KP_GREATER = SDL.Input.Keycode.KP_GREATER,
	KP_HASH = SDL.Input.Keycode.KP_HASH,
	KP_HEXADECIMAL = SDL.Input.Keycode.KP_HEXADECIMAL,
	KP_LEFTBRACE = SDL.Input.Keycode.KP_LEFTBRACE,
	KP_LEFTPAREN = SDL.Input.Keycode.KP_LEFTPAREN,
	KP_LESS = SDL.Input.Keycode.KP_LESS,
	KP_MEMADD = SDL.Input.Keycode.KP_MEMADD,
	KP_MEMCLEAR = SDL.Input.Keycode.KP_MEMCLEAR,
	KP_MEMDIVIDE = SDL.Input.Keycode.KP_MEMDIVIDE,
	KP_MEMMULTIPLY = SDL.Input.Keycode.KP_MEMMULTIPLY,
	KP_MEMRECALL = SDL.Input.Keycode.KP_MEMRECALL,
	KP_MEMSTORE = SDL.Input.Keycode.KP_MEMSTORE,
	KP_MEMSUBTRACT = SDL.Input.Keycode.KP_MEMSUBTRACT,
	KP_MINUS = SDL.Input.Keycode.KP_MINUS,
	KP_MULTIPLY = SDL.Input.Keycode.KP_MULTIPLY,
	KP_OCTAL = SDL.Input.Keycode.KP_OCTAL,
	KP_PERCENT = SDL.Input.Keycode.KP_PERCENT,
	KP_PERIOD = SDL.Input.Keycode.KP_PERIOD,
	KP_PLUS = SDL.Input.Keycode.KP_PLUS,
	KP_PLUSMINUS = SDL.Input.Keycode.KP_PLUSMINUS,
	KP_POWER = SDL.Input.Keycode.KP_POWER,
	KP_RIGHTBRACE = SDL.Input.Keycode.KP_RIGHTBRACE,
	KP_RIGHTPAREN = SDL.Input.Keycode.KP_RIGHTPAREN,
	KP_SPACE = SDL.Input.Keycode.KP_SPACE,
	KP_TAB = SDL.Input.Keycode.KP_TAB,
	KP_VERTICALBAR = SDL.Input.Keycode.KP_VERTICALBAR,
	KP_XOR = SDL.Input.Keycode.KP_XOR,
	LALT = SDL.Input.Keycode.LALT,
	LCTRL = SDL.Input.Keycode.LCTRL,
	LEFT = SDL.Input.Keycode.LEFT,
	LEFTBRACKET = SDL.Input.Keycode.LEFTBRACKET,
	LEFTPAREN = SDL.Input.Keycode.LEFTPAREN,
	LESS = SDL.Input.Keycode.LESS,
	LGUI = SDL.Input.Keycode.LGUI,
	LSHIFT = SDL.Input.Keycode.LSHIFT,
	MAIL = SDL.Input.Keycode.MAIL,
	MEDIASELECT = SDL.Input.Keycode.MEDIASELECT,
	MENU = SDL.Input.Keycode.MENU,
	MINUS = SDL.Input.Keycode.MINUS,
	MODE = SDL.Input.Keycode.MODE,
	MUTE = SDL.Input.Keycode.MUTE,
	NINE = SDL.Input.Keycode.NINE,
	NUMLOCKCLEAR = SDL.Input.Keycode.NUMLOCKCLEAR,
	ONE = SDL.Input.Keycode.ONE,
	OPER = SDL.Input.Keycode.OPER,
	OUT = SDL.Input.Keycode.OUT,
	PAGEDOWN = SDL.Input.Keycode.PAGEDOWN,
	PAGEUP = SDL.Input.Keycode.PAGEUP,
	PASTE = SDL.Input.Keycode.PASTE,
	PAUSE = SDL.Input.Keycode.PAUSE,
	PERCENT = SDL.Input.Keycode.PERCENT,
	PERIOD = SDL.Input.Keycode.PERIOD,
	PLUS = SDL.Input.Keycode.PLUS,
	POWER = SDL.Input.Keycode.POWER,
	PRINTSCREEN = SDL.Input.Keycode.PRINTSCREEN,
	PRIOR = SDL.Input.Keycode.PRIOR,
	QUESTION = SDL.Input.Keycode.QUESTION,
	QUOTE = SDL.Input.Keycode.QUOTE,
	QUOTEDBL = SDL.Input.Keycode.QUOTEDBL,
	RALT = SDL.Input.Keycode.RALT,
	RCTRL = SDL.Input.Keycode.RCTRL,
	RETURN = SDL.Input.Keycode.RETURN,
	RETURN2 = SDL.Input.Keycode.RETURN2,
	RGUI = SDL.Input.Keycode.RGUI,
	RIGHT = SDL.Input.Keycode.RIGHT,
	RIGHTBRACKET = SDL.Input.Keycode.RIGHTBRACKET,
	RIGHTPAREN = SDL.Input.Keycode.RIGHTPAREN,
	RSHIFT = SDL.Input.Keycode.RSHIFT,
	SCROLLLOCK = SDL.Input.Keycode.SCROLLLOCK,
	SELECT = SDL.Input.Keycode.SELECT,
	SEMICOLON = SDL.Input.Keycode.SEMICOLON,
	SEPARATOR = SDL.Input.Keycode.SEPARATOR,
	SEVEN = SDL.Input.Keycode.SEVEN,
	SIX = SDL.Input.Keycode.SIX,
	SLASH = SDL.Input.Keycode.SLASH,
	SLEEP = SDL.Input.Keycode.SLEEP,
	SPACE = SDL.Input.Keycode.SPACE,
	STOP = SDL.Input.Keycode.STOP,
	SYSREQ = SDL.Input.Keycode.SYSREQ,
	TAB = SDL.Input.Keycode.TAB,
	THOUSANDSSEPARATOR = SDL.Input.Keycode.THOUSANDSSEPARATOR,
	THREE = SDL.Input.Keycode.THREE,
	TWO = SDL.Input.Keycode.TWO,
	UNDERSCORE = SDL.Input.Keycode.UNDERSCORE,
	UNDO = SDL.Input.Keycode.UNDO,
	UNKNOWN = SDL.Input.Keycode.UNKNOWN,
	UP = SDL.Input.Keycode.UP,
	VOLUMEDOWN = SDL.Input.Keycode.VOLUMEDOWN,
	VOLUMEUP = SDL.Input.Keycode.VOLUMEUP,
	WWW = SDL.Input.Keycode.WWW,
	ZERO = SDL.Input.Keycode.ZERO,
	a = SDL.Input.Keycode.a,
	b = SDL.Input.Keycode.b,
	c = SDL.Input.Keycode.c,
	d = SDL.Input.Keycode.d,
	e = SDL.Input.Keycode.e,
	f = SDL.Input.Keycode.f,
	g = SDL.Input.Keycode.g,
	h = SDL.Input.Keycode.h,
	i = SDL.Input.Keycode.i,
	j = SDL.Input.Keycode.j,
	k = SDL.Input.Keycode.k,
	l = SDL.Input.Keycode.l,
	m = SDL.Input.Keycode.m,
	n = SDL.Input.Keycode.n,
	o = SDL.Input.Keycode.o,
	p = SDL.Input.Keycode.p,
	q = SDL.Input.Keycode.q,
	r = SDL.Input.Keycode.r,
	s = SDL.Input.Keycode.s,
	t = SDL.Input.Keycode.t,
	u = SDL.Input.Keycode.u,
	v = SDL.Input.Keycode.v,
	w = SDL.Input.Keycode.w,
	x = SDL.Input.Keycode.x,
	y = SDL.Input.Keycode.y,
	z = SDL.Input.Keycode.z
}


public class Vgl.Event : Object {
	public Event() {

	}

	public bool pool() {
		if (SDL.Event.poll (out event) >= 1)
			return true;
		else
			return false;
	}

	public EventType getType () {
		return (Vgl.EventType)event.type;
	}

	public Vgl.KeyCode getkey () {
		return (Vgl.KeyCode)event.key.keysym.sym;
	} 
	
	public unowned string getkey_name () {
		return event.key.keysym.sym.get_name ();
	} 

	SDL.Event event;

}
